export interface EntryData {
  Entry: string;
  difficulty: number;
}


export const bingoData: EntryData[] = [
  { Entry: 'Hund på tur', difficulty: 1 },
  { Entry: 'Katt', difficulty: 3 },
  { Entry: 'Flaggermus', difficulty: 2 },
  { Entry: 'Måke', difficulty: 1 },
  { Entry: 'Fyr i baris', difficulty: 2.5 },
  { Entry: 'Shit kids', difficulty: 2.5 },
  { Entry: 'Da/Ai', difficulty: 2.5 },
  { Entry: 'Sirene forbi', difficulty: 2 },
  { Entry: 'Folk på jobb', difficulty: 2 },
  { Entry: 'Folk på takterasse', difficulty: 2 },
  { Entry: 'Vindu åpnes', difficulty: 1 },
  { Entry: 'Bi*** i vindu', difficulty: 3 },
  { Entry: 'Nabo duolingo', difficulty: 3 },
  { Entry: 'Monstera i vindu', difficulty: 2.5 },
  { Entry: 'Turist Asian', difficulty: 2.5 },
  { Entry: 'Løp til buss/tog', difficulty: 2.5 },
  { Entry: 'Røyker', difficulty: 1 },
  { Entry: 'Farga lys', difficulty: 2 },
  { Entry: 'Post / søppel', difficulty: 2.5 },
  { Entry: 'Folk på terrasse', difficulty: 1 },
  { Entry: 'Lekestativ brukes', difficulty: 1.5 },
  { Entry: 'Klinings', difficulty: 3 },
  { Entry: 'TV på hos nabo', difficulty: 1 },
  { Entry: 'Vi blir sett', difficulty: 3 },
  { Entry: 'Skatebord / rulleskøyter / sparkesykkel', difficulty: 2 },
  { Entry: 'Person på gangbro', difficulty: 1 },
  { Entry: 'Gruppe (3 eller flere)', difficulty: 2.5 },
  { Entry: 'Stor koffert', difficulty: 3 },
  { Entry: 'Begge Inngangsporter brukes', difficulty: 2 },
  { Entry: 'Gardin opp / igjen', difficulty: 3 },
  { Entry: 'Foodora / matbud', difficulty: 2 },
  { Entry: 'Tog', difficulty: 1 },
  { Entry: 'Vanne planter', difficulty: 3 },
  { Entry: 'Vindeltrapp', difficulty: 3 },
  { Entry: 'Dør ved trapp', difficulty: 1 },
  { Entry: 'Fly', difficulty: 1 },
  { Entry: 'Vi booker greie i kalender', difficulty: 2 },
];
